### PR TITLE
DM-13110: compress raw r-band data

### PR DESCRIPTION
**Pull request by PaulPrice**
In order to demonstrate that we can deal with FITS tile-compressed raw
data, compress the r-band raw data (fpack -F raw/HSC9033[34]*.fits).
Explicitly not compressing the i-band raw data, to ensure we can still
protect that mode of operating too.

### CODE REVIEW

**Comment by RobertLuptonTheGood** [comment]
Is `fpack -F raw/HSC9033[34]*.fits` identical to the output produced by writing compressed Images from afw?

**Comment by PaulPrice** [comment]
It may not be completely identical (there could be minor header differences?), but we never write raw images with afw (they are directly from the telescope).

**Comment by RobertLuptonTheGood** [comment]
OK, good to merge.  I assume that the other changesets confirm that these files are correct.

**Comment by RobertLuptonTheGood** [comment]
Oops, didn't mean to close it.

**Pull request merged**
